---
- name: Converge
  hosts: all
  tasks:
    - name: "Apply all available updates."
      include_role:
        name: "rossijonas.dnfupdate"
    - name: "Apply security updates only."
      include_role:
        name: "rossijonas.dnfupdate"
      vars:
        dnfupdate_security_only: true
