name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-go@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          # install podman
          apt install curl wget gnupg2 -y
          source /etc/os-release
          sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
          wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_${VERSION_ID}/Release.key -O- | apt-key add -}
          apt-get update -qq -y
          apt-get -qq --yes install podman
          # install ansible and molecule
          pip3 install yamllint ansible-lint ansible molecule[podman]

      - name: Molecule test
        run: molecule test
