name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-go@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          # install podman
          # sudo apt install curl wget gnupg2 -y
          # source /etc/os-release
          # sudo sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
          # sudo wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_${VERSION_ID}/Release.key -O- | sudo tee /etc/apt/trusted.gpg.d/Release.key}
          # sudo apt update -qq -y
          # sudo apt -qq --yes install podman
          # install ansible and molecule
          sudo apt install podman
          sudo sed -i "s/# unqualified-search-registries.*/unqualified-search-registries\ =\ [\"docker.io\"]/" /etc/containers/registries.conf
          pip3 install yamllint ansible-lint ansible molecule[podman]

      - name: Molecule test
        run: molecule test
